### ISSUE TITLE
TODO 

### ISSUE THREAD

**Issue by moonsdust** [moonsdust/SheepJumpAI#1]
- [ ] Add speed slider
- [x] Add highest score (based on time) 
- [x] Add indication of number of generations somewhere
- [x] Add number of sheep still alive
